In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [4]:
df = pd.read_csv('temp/Final_Dataset.csv')
df = df.sample(frac = 1)
df

Unnamed: 0                                            tx_hash  \
966095      966095  cc7e579f6c05f88354920330bde4eb3d0d0580ed3a29c5...   
917860      917860  8722d27dd2ab249ca41031f8f15702988bfa99939df05c...   
144462      144462  c5064611bd4ee914b1c576e5c4aca11dd8ed2d090a4ba0...   
51314        51314  5aab4be201a21829fbee2454e4a06e6c58b7b6c8c98022...   
499662      499662  e2def90992fc37c1928a5b8820b712b974f98fdb0aabeb...   
...            ...                                                ...   
498402      498402  9703f48387ab70465d39c795022b5ad260a7eb6e26f6f2...   
877193      877193  c6d3730003ebeb9da5cca28c1996f632b0785a07ce4273...   
534583      534583  4b1af282056b21d83572b177936dc32769fbcc885d9c75...   
761587      761587  f18de83ef2786ea0778c0b10ebe11d1793dc6e5a4edfd4...   
189928      189928  41c555bbd050ecfc2f0022de461f513d1ee94e62d53897...   

        indegree  outdegree   in_btc  out_btc  total_btc  mean_in_btc  \
966095       1.0        1.0   4.3400   4.3400     8.6800       4.3400   
917860       2.0        2.0   5.6900   5.6900    11.3800       2.8450   
144462       1.0        1.0   0.0100   0.0100     0.0200       0.0100   
51314        0.0        1.0   0.0000  50.0000    50.0000       0.0000   
499662       3.0        1.0   0.0600   0.0100     0.0700       0.0200   
...          ...        ...      ...      ...        ...          ...   
498402       1.0        2.0  79.8100  79.8100   159.6200      79.8100   
877193       1.0        2.0  60.1418  60.1418   120.2836      60.1418   
534583       1.0        2.0   0.0200   0.0200     0.0400       0.0200   
761587       4.0        2.0   1.2000   1.1900     2.3900       0.3000   
189928       1.0        0.0   0.0200   0.0000     0.0200       0.0200   

        mean_out_btc  in_malicious  out_malicious  is_malicious  \
966095        4.3400           0.0            0.0           0.0   
917860        2.8450           0.0            0.0           0.0   
144462        0.0100           0.0            0.0           0.0   
51314        50.0000           0.0            0.0           0.0   
499662        0.0100           0.0            0.0           0.0   
...              ...           ...            ...           ...   
498402       39.9050           0.0            0.0           0.0   
877193       30.0709           0.0            0.0           0.0   
534583        0.0100           0.0            0.0           0.0   
761587        0.5950           0.0            0.0           0.0   
189928        0.0000           0.0            0.0           0.0   

        all_malicious  out_and_tx_malicious  
966095            0.0                   0.0  
917860            0.0                   0.0  
144462            0.0                   0.0  
51314             0.0                   0.0  
499662            0.0                   0.0  
...               ...                   ...  
498402            0.0                   0.0  
877193            0.0                   0.0  
534583            0.0                   0.0  
761587            0.0                   0.0  
189928            0.0                   0.0  

[1000105 rows x 14 columns]

In [5]:
df.drop('Unnamed: 0', axis=1, inplace=True)
df.drop('tx_hash', axis=1, inplace=True)
df.drop('in_malicious', axis=1, inplace=True)
df.drop('out_malicious', axis=1, inplace=True)
df.drop('is_malicious', axis=1, inplace=True)
df.drop('all_malicious', axis=1, inplace=True)

In [6]:
print('No Frauds', round(df['out_and_tx_malicious'].value_counts()[0]/len(df) * 100,7), '% of the dataset')
print('Frauds', round(df['out_and_tx_malicious'].value_counts()[1]/len(df) * 100,5), '% of the dataset')

No Frauds 99.9892011 % of the dataset
Frauds 0.0108 % of the dataset


In [7]:
df['out_and_tx_malicious'].value_counts()

0.0    999997
1.0       108
Name: out_and_tx_malicious, dtype: int64

In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

scaled_df = df.copy()
scaled_df['indegree'] = scaler.fit_transform(scaled_df['indegree'].values.reshape(-1,1))
scaled_df['outdegree']= scaler.fit_transform(scaled_df['outdegree'].values.reshape(-1,1))
scaled_df['in_btc'] = scaler.fit_transform(scaled_df['in_btc'].values.reshape(-1,1))
scaled_df['out_btc']= scaler.fit_transform(scaled_df['out_btc'].values.reshape(-1,1))
scaled_df['total_btc']= scaler.fit_transform(scaled_df['total_btc'].values.reshape(-1,1))
scaled_df['mean_in_btc']= scaler.fit_transform(scaled_df['mean_in_btc'].values.reshape(-1,1))
scaled_df['mean_out_btc']= scaler.fit_transform(scaled_df['mean_out_btc'].values.reshape(-1,1))

In [9]:
scaled_df

indegree  outdegree    in_btc   out_btc  total_btc  mean_in_btc  \
966095 -0.110597  -0.161340 -0.061613 -0.063148  -0.062767    -0.061096   
917860  0.079472   0.034657 -0.061032 -0.062566  -0.062182    -0.061806   
144462 -0.110597  -0.161340 -0.063476 -0.065014  -0.064644    -0.063151   
51314  -0.300667  -0.161340 -0.063481 -0.043470  -0.053815    -0.063156   
499662  0.269542  -0.161340 -0.063455 -0.065014  -0.064633    -0.063146   
...          ...        ...       ...       ...        ...          ...   
498402 -0.110597   0.034657 -0.029134 -0.030623  -0.030064    -0.025281   
877193 -0.110597   0.034657 -0.037599 -0.039100  -0.038587    -0.034615   
534583 -0.110597   0.034657 -0.063472 -0.065010  -0.064639    -0.063146   
761587  0.459612   0.034657 -0.062964 -0.064506  -0.064130    -0.063013   
189928 -0.110597  -0.357337 -0.063472 -0.065019  -0.064644    -0.063146   

        mean_out_btc  out_and_tx_malicious  
966095     -0.061866                   0.0  
917860     -0.062945                   0.0  
144462     -0.064993                   0.0  
51314      -0.028891                   0.0  
499662     -0.064993                   0.0  
...              ...                   ...  
498402     -0.036182                   0.0  
877193     -0.043284                   0.0  
534583     -0.064993                   0.0  
761587     -0.064570                   0.0  
189928     -0.065000                   0.0  

[1000105 rows x 8 columns]

In [28]:
temp = scaled_df[scaled_df['out_and_tx_malicious']==1.0]
temp

indegree  outdegree    in_btc   out_btc  total_btc  mean_in_btc  \
1000054  5.211352   0.034657  6.873763  6.882144   6.920646     0.200633   
1000059  0.079472   0.034657 -0.037416 -0.038917  -0.038403    -0.048785   
1000062  0.839751  -0.161340 -0.063040 -0.064577  -0.064204    -0.063075   
1000060  1.600029   0.034657  3.754674  3.758595   3.779952     0.357882   
1000029  1.029820   0.034657 -0.050564 -0.052084  -0.051642    -0.061121   
...           ...        ...       ...       ...        ...          ...   
1000038  0.079472   0.034657  1.726772  1.727794   1.738005     0.923922   
1000087 -0.110597   0.034657 -0.044945 -0.046456  -0.045983    -0.042715   
1000044  3.880865  -0.357337  0.231558 -0.065019   0.083893    -0.048367   
1000065 -0.110597   0.034657  0.151001  0.149770   0.151319     0.173359   
1000010  0.079472   0.034657 -0.063246 -0.064784  -0.064411    -0.063026   

         mean_out_btc  out_and_tx_malicious  
1000054      5.755722                   1.0  
1000059     -0.043131                   1.0  
1000062     -0.064260                   1.0  
1000060      3.138638                   1.0  
1000029     -0.054162                   1.0  
...               ...                   ...  
1000038      1.437119                   1.0  
1000087     -0.049447                   1.0  
1000044     -0.065000                   1.0  
1000065      0.114962                   1.0  
1000010     -0.064803                   1.0  

[108 rows x 8 columns]

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(scaled_df.iloc[:,:-1], scaled_df['out_and_tx_malicious'], test_size = 0.2, random_state=2)

In [11]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(800084, 7)
(200021, 7)
(800084,)
(200021,)


In [17]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import pickle


In [18]:
def decision_tree_classification(X_train, y_train, X_test, y_test):
    # initialize object for DecisionTreeClassifier class
    dt_classifier = DecisionTreeClassifier()
    # train model by using fit method
    print("Model training starts........")
    dt_classifier.fit(X_train, y_train.values.ravel())
    print("Model training completed")
    acc_score = dt_classifier.score(X_test, y_test)
    print(f'Accuracy of model on test dataset :- {acc_score}')
    # predict result using test dataset
    y_pred = dt_classifier.predict(X_test)
    # confusion matrix
    print(f"Confusion Matrix :- \n {confusion_matrix(y_test, y_pred)}")
    # classification report for f1-score
    print(f"Classification Report :- \n {classification_report(y_test, y_pred)}")
    
    with open('dt_model','wb') as f:
        pickle.dump(dt_classifier,f)
    print("Saved as dt_model")
    

In [19]:
decision_tree_classification(X_train, y_train, X_test, y_test)

Model training starts........
Model training completed
Accuracy of model on test dataset :- 0.9998250183730708
Confusion Matrix :- 
 [[199986     12]
 [    23      0]]
Classification Report :- 
               precision    recall  f1-score   support

         0.0       1.00      1.00      1.00    199998
         1.0       0.00      0.00      0.00        23

    accuracy                           1.00    200021
   macro avg       0.50      0.50      0.50    200021
weighted avg       1.00      1.00      1.00    200021

Saved as dt_model


In [15]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

def random_forest_classifier(X_train, y_train, X_test, y_test):
     # initialize object for DecisionTreeClassifier class
     rf_classifier = RandomForestClassifier(n_estimators=50)
     # train model by using fit method
     print("Model training starts........")
     rf_classifier.fit(X_train, y_train.values.ravel())
     acc_score = rf_classifier.score(X_test, y_test)
     print(f'Accuracy of model on test dataset :- {acc_score}')
     # predict result using test dataset
     y_pred = rf_classifier.predict(X_test)
     # confusion matrix
     print(f"Confusion Matrix :- \n {confusion_matrix(y_test, y_pred)}")
     # classification report for f1-score
     print(f"Classification Report :- \n {classification_report(y_test, y_pred)}")


# calling random_forest_classifier
random_forest_classifier(X_train, y_train, X_test, y_test)

Model training starts........
Accuracy of model on test dataset :- 0.9998650141735118
Confusion Matrix :- 
 [[199994      4]
 [    23      0]]
Classification Report :- 
               precision    recall  f1-score   support

         0.0       1.00      1.00      1.00    199998
         1.0       0.00      0.00      0.00        23

    accuracy                           1.00    200021
   macro avg       0.50      0.50      0.50    200021
weighted avg       1.00      1.00      1.00    200021



In [16]:
model_prediction = dt_classifier.predict(-0.110597,	0.034657, -0.043030, -0.044539,	-0.044056, -0.040605, -0.047841	)
model_prediction

NameError: name 'dt_classifier' is not defined

In [20]:
with open('dt_model', 'rb') as f:
    model = pickle.load(f)

In [25]:
model_prediction = model.predict([[-0.110597,	0.034657, -0.043030, -0.044539,	-0.044056, -0.040605, -0.047841]])
model_prediction

C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"


array([0.])

In [31]:
model_prediction = model.predict([[5.211352,	0.034657,	6.873763,	6.882144,	6.920646,	0.200633,	5.755722]])
model_prediction[0]


C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"


0.0